import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { AppProviders } from "@/components/providers/AppProviders";
import { CanvasProvider } from "./fitobject/_components/canvas/CanvasContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CanvasProvider>
        <html lang="en">
          <body className={`font-lexend antialiased`}>
            <AppProviders>{children}</AppProviders>
          </body>
        </html>
      </CanvasProvider>
    </ClerkProvider>
  );
}
